[project]
name = "crewai-company-research"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agentops>=0.4.21",
    "crewai[anthropic,gemini]>=1.6.0",
    "crewai-tools>=1.6.0",
    "litellm>=1.80.5",
]
